name: wave_tracing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - matplotlib
  - numpy
  - scipy
  - netcdf4
  - xarray
  - pyproj
  - cartopy
  - pip
  - pyyaml
  - ipython
  - cmocean
  - jupyterlab
  - pytest
  - importlib_resources
